config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    #path("", TemplateView.as_view(template_name="pages/home.html"),name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    # path("users/", include("djangogram.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # /
    path("", include("djangogram.users.urls", namespace="users")),

    # /posts/
    path("posts/", include("djangogram.posts.urls", namespace="posts"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

djangogram/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),   
    path('create/', views.post_create, name='post_create'),
    path('<int:post_id>/update', views.post_update, name="post_update"),
    path('<int:post_id>/comment_create', views.comment_create, name="comment_create"),
    path('<int:comment_id>/commnet_delete', views.comment_delete, name="comment_delete"),
    path('<int:post_id>/post_like', views.post_like, name="post_like"),
    path('search/', views.search, name='post_search'),
]

djangogram/users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('', views.main, name='main'),
    path('signup/', views.signup, name='signup'),
]

djangogram/posts/models.py
from django.db import models
from djangogram.users import models as user_model

# Create your models here.
class TimeStameModel(models.Model):
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

class Post(TimeStameModel):
    author = models.ForeignKey(user_model.User, null=True, on_delete=models.CASCADE, related_name='post_author')
    image = models.ImageField(blank=False)
    caption = models.TextField(blank=False)
    image_likes = models.ManyToManyField(user_model.User, blank=True, related_name='post_image_likes') 

    def __str__(self):
        return f"{self.author}: {self.caption}"

class Comment(TimeStameModel):
    author = models.ForeignKey(user_model.User, null=True, on_delete=models.CASCADE, related_name='comment_author')
    posts = models.ForeignKey(Post, null=True, on_delete=models.CASCADE, related_name='comment_post')
    contents = models.TextField(blank=True)

    def __str__(self):
        return f"{self.author}:{self.contents}"

djangogram/users/models.py
from ast import BinOp
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    GENDER_CHOICES = [
        ('M','Male'),
        ('F','Female'),
        ('C','Custom'),
    ]

    #: First and last name do not cover name patterns around the globe
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    user_name = models.CharField(blank=True, max_length=255)
    profile_photo =models.ImageField(blank=True)
    website = models.URLField(blank=True)
    bio = models.TextField(blank=True)
    email = models.CharField(blank=True,max_length=255)
    phone_number = models.CharField(blank=True, max_length=255)
    gender = models.CharField(blank=True, choices=GENDER_CHOICES, max_length=255)
    followers = models.ManyToManyField("self")
    following = models.ManyToManyField("self")


    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

djangogram/posts/forms.py
from django import forms
from .models import Post, Comment

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["caption", "image"]

        labels =  {
            "caption" : "내용",
            "image" : "사진"
        }

class UpdatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields= ["caption"]

class CommentForm(forms.ModelForm):
    contents = forms.CharField(widget=forms.Textarea, label="")
    class Meta:
        model = Comment
        fields = ["contents"]

djangogram/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django import forms as django_forms

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User

class UserCreationForm(forms.UserCreationForm):
    
    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username":_("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

        def clean_username(self):
            username = self.cleaned_data["username"]

            try :
                User.objects.get(username=username)
            except User.DoesNotExist:
                return username
            
            raise ValidationError(self.error_messages["duplicate_username"])

class SignUpForm(django_forms.ModelForm):
    class Meta:
        model = User
        fields = ['email','name','username','password']

#        labels = {
#            'email': '이메일주소',
#            'name': '성명',
#            'username': '사용자 이름' ,
#            'password': '비밀번호'
#        }

        widgets ={
            'email' : django_forms.TextInput(attrs={'placeholder': '이메일주소'}),
            'name' : django_forms.TextInput(attrs={'placeholder':'성명'}),
            'username' : django_forms.TextInput(attrs={'placeholder':'사용자 이름'}),
            'password' : django_forms.PasswordInput(attrs={'placeholder':'비밀번호'}),
        }

    def save(self,commit=True):
        user=super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

djangogram/posts/views.py
from urllib import response
from django.shortcuts import redirect, render, get_object_or_404
from django.db.models import Q
from djangogram.users.models import User as user_model
from django.urls import reverse
from django.http import JsonResponse

from . import models, serializers
from .forms import CreatePostForm, CommentForm, UpdatePostForm

# Create your views here.
def index(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            comment_form = CommentForm()
            user = get_object_or_404(user_model, pk=request.user.id)
            follwing = user.following.all()
            posts = models.Post.objects.filter(
                Q(author__in=follwing) | Q(author=user)
            ).order_by("-create_at")

            serializer = serializers.PostSerializer(posts, many=True)
            print(serializer.data)
            
            return render(request, 'posts/main.html', {"posts": serializer.data, "comment_form":comment_form})

def post_create(request):
    if request.method == 'GET':
        form = CreatePostForm()    
        return render(request, 'posts/post_create.html', {"form":form})
        
    elif request.method == 'POST':
        if request.user.is_authenticated:
            user = get_object_or_404(user_model, pk=request.user.id)
    
        # image = request.FILES['image']
        # caption = request.POST['caption']

#            new_post = models.Post.objects.create(
#                author = user,
#                image = image,
#                caption = caption
#            )
#            new_post.save()

            form = CreatePostForm(request.POST, request.FILES)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = user
                post.save()
            else:
                print(form.errors)

            return render(request,'posts:index')
        else :
            return render(request, 'users/main.html')

def post_update(request, post_id):
    if request.user.is_authenticated:
        # 작성자 체크
        post = get_object_or_404(models.Post, pk=post_id)
        if request.user != post.author:
            return redirect(reverse('posts:index'))
        
        # GET 요청
        if request.method == 'GET':
            form = UpdatePostForm(instance=post)
            return render(
                request, 'posts/post_update.html',{"form":form, "post":post }
            )
        elif request.method == 'POST':
            form = UpdatePostForm(request.POST)
            if form.is_valid():
                post.caption = form.cleaned_data['caption']
                post.save()
            return redirect(reverse('posts:index'))

    else :
        return render(request,'users/main.html')

def comment_create(request, post_id):
    if request.user.is_authenticated:
        post = get_object_or_404(models.Post, pk=post_id)

        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.posts = post
            comment.save()

            return redirect(reverse('posts:index') + "#comment-"+str(comment.id))
        
        else : 
            return render(request, 'users/main.html')

def comment_delete(request, comment_id):
    if request.user.is_authenticated:
        comment = get_object_or_404(models.Comment, pk=comment_id)
        if request.user == comment.author:
            comment.delete()

        return redirect(reverse('posts:index'))

    else:
        return render(request, 'users/main.html')

def post_like(request, post_id):
    response_body = {"result": ""}

    if request.user.is_authenticated:
        if request.method == "POST":
            post = get_object_or_404(models.Post, pk=post_id)
            existed_user = post.image_likes.filter(pk=request.user.id).exists()

            if existed_user:
                # 좋아요 누른 상태일 때는 "좋아요 취소"
                post.image_likes.remove(request.user)
                response_body["result"] = "dislike"

            else:
                # 좋아요가 아닐때 "좋아요"
                post.image_likes.add(request.user)
                response_body["result"] = "like"

            post.save()
            return JsonResponse(status=200, data=response_body)

    else:
        return JsonResponse(status=403, data=response_body)

def search(request):
    if request.user.is_authenticated:
        if request.method == "GET":
            searchKeyword = request.GET.get("q", "")
            comment_form = CommentForm()

            user = get_object_or_404(user_model, pk=request.user.id)
            following = user.following.all()
            posts = models.Post.objects.filter(
                (Q(author__in=following) | Q(author=user)) & Q(caption__contains=searchKeyword)
            ).order_by("-create_at")

            serializer = serializers.PostSerializer(posts, many=True)
            print(serializer.data)

            return render(
                request,
                'posts/main.html',
                {"posts": serializer.data, "comment_form": comment_form}
            )

    else:
        return render(request, 'users/main.html') 

djangogram/users/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse 
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from .forms import SignUpForm

def main(request):
    if request.method == 'GET':
        return render(request, 'users/main.html')

    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None : 
            login(request, user)
            return HttpResponseRedirect(reverse('posts:index'))
        else :
            return render(request, 'users/main.html')


def signup(request):
    if request.method == 'GET':
        form = SignUpForm()

        return render(request, 'users/signup.html',{'form':form})
        
    elif request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(request, username=username, password=password)

            if user is not None : 
                login(request, user)
                return HttpResponseRedirect(reverse('posts:index'))

        return render(request, 'users/main.html')

djangogram/templates/posts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/posts/base.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/posts/header.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/posts/main.css'%}">


    <!-- Font Awesome  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Document</title>
</head>
<body>
    <div class="header">
        {% include "posts/header.html" %}
    </div>

    <div>
        {% block content %}  {% endblock %}
    </div>
    <script type="text/javascript" src="{% static 'js/posts.js' %}"></script>
</body>
</html> 

djangogram/templates/posts/header.html
{% load static %}
<header>
    <div class="header-box">
        <div class="main-img">
            <a href="{% url 'posts:index' %}">
                <img src="{% static 'images/posts/main_logo.png'%}" alt="logo">
            </a>
        </div>
        <div class="search">
            <form action="{% url 'posts:post_search' %}" method="GET">
                <input type="text" name="q" placeholder="Search">
            </form>
        </div>
        <div class="header-right">
            <div>
                <a href="{% url 'posts:post_create' %}">
                    <i class="fa fa-plus-circle fa-2x"></i>
                </a>
            </div>
            <div>
                <a href="#">
                    <i class="fa fa-user fa-2x"></i>
                </a>
            </div>
        </div>
    </div>
</header> 

djangogram/templates/posts/index.html
Here is index.html

djangogram/templates/posts/main.html
{% extends "posts/base.html" %}
{% load static %}
{% block content %}

{% for post in posts %}
<div class="post-box">
        <!-- HEADER -->
        <div class="header">
            <div class="profile">
                {% if post.author.profile_photo != None %}
                    <img src="{{ post.author.profile_photo }}">
                {% else %}
                    <img src="{% static 'images/posts/no_avatar.png' %}">
                {% endif %}
                <div>
                    {{ post.author.username }}
                </div>
            </div>
            {% if user.id == post.author.id %}
                <div class="icon">
                    <a href="{% url 'posts:post_update' post.id %}">
                        <i class="fa fa-pencil fa1x"></i>
                    </a>               
                    <i class="fa fa-trash-o fa1x"></i>
                </div>
            {% endif %}
        </div>

        <!-- IMAGE -->
        <img class="post-image" src="{{ post.image }}">

        <!-- IMAGE-BUTTON -->
        <button id="like-button-{{ post.id }}" onclick="handleLikeClick(this.id)">
        {% if user.id in post.image_likes %}
            <i class="fa fa-heart fa-2x"></i>
        {% else %}
            <i class="fa fa-heart-o fa-2x"></i>
        {% endif %}
        </button>
        
        <div class="desc-box">
            <!-- IMAGE-DESCRIPTION -->
            <div class="image-desc">
                <b>{{ post.author.username }}</b>
                {{ post.caption }}
            </div>

            <!-- COMMENT -->
            <div class="comment">
                {% for comment in post.comment_post %}
                    <div id="comment-{{ comment.id }}">
                        <b>{{ comment.author.username }}</b>
                        {{ comment.contents }}
                        {% if user.id == comment.author.id %}
                            <a href="{% url 'posts:comment_delete' comment.id %}">
                                <i class="fa fa-trash-o fa1x"></i>
                    </div>
                        {% endif %}
                {% endfor %}
            </div>
        </div>

        <!-- COMMENT INPUT -->
        <div class="comment-input">
            <form action="{% url 'posts:comment_create' post.id %}" method="post">
                {% csrf_token %}
                {{ comment_form }}
                <input type="submit" value="Post">
            </form>
        </div>

    </div>

{% endfor %}

{% endblock content %}

djangogram/templates/posts/post_create.html
{% extends "posts/base.html" %}

{% block content %}

<div class="post-create">
    <div>
        Create Post
    </div>
    
    <div class="form">
        <form action="{% url 'posts:post_create' %}"
                    method="post"
                    enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Create">
        </form>

</div>

{% endblock content %}

djangogram/templates/posts/post_update.html
{% extends "posts/base.html" %}

{% block content %}

<div class="post-create">
    <div>
        Update Post
    </div>
    
    <div class="form">
        <form action="{% url 'posts:post_update' post.id %}"
                    method="post"
                    enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update">
        </form>

</div>

{% endblock content %}